homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'

#urlpatterns
urlpatterns = [
    path('', views.top, name='top'),#views.py の関数を実行
    path('myroom/', views.myroom, name='myroom'),#views.py の関数を実行
    #path('', views.top),#追加
    path('coordinator/', views.coordinator, name='coordinator'),#増えた
    path('register/', views.register, name='register'),#増えた
    path('aboutus/', views.aboutus, name='aboutus'),#増えた
    path('contact/', views.contact, name='contact'),#増えた
    path('terms_of_service/', views.terms_of_service, name='terms_of_service'),#増えた
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),#増えた
]

idealroom/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include #追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),#追加
    #path('resume/', resume,),#増えた
]

homepage/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Coordinator(models.Model):#QuerySet
    STARS = (
        (1, '★☆☆☆☆'),
        (2, '★★☆☆☆'),
        (3, '★★★☆☆'),
        (4, '★★★★☆'),
        (5, '★★★★★'),
    )
    name = models.CharField('氏名', max_length=255)
    furigana = models.CharField('ふりがな', max_length=255)
    picture = models.CharField('写真', max_length=255)
    text = models.TextField('メッセージ')
    stars = models.IntegerField('星の数', choices=STARS)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    # 追加 管理画面の登録情報の表示名を変える
    def __str__(self):
        return '名前：{}'.format(self.name)

        

class Coordinator2(models.Model):#QuerySet
    STARS = (
        (1, '★☆☆☆☆'),
        (2, '★★☆☆☆'),
        (3, '★★★☆☆'),
        (4, '★★★★☆'),
        (5, '★★★★★'),
    )
    name = models.CharField('氏名', max_length=255)
    furigana = models.CharField('ふりがな', max_length=255)
    picture = models.CharField('写真', max_length=255)
    text = models.TextField('メッセージ')
    stars = models.IntegerField('星の数', choices=STARS)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    # 追加 管理画面の登録情報の表示名を変える
    def __str__(self):
        return '名前：{}'.format(self.name)

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse #追加
from django.template import loader#追加
from .models import Coordinator
from .models import Coordinator2
# Create your views here.

#関数を追加
#def top(request):
#    html = loader.render_to_string('homepage/index.html')
#    return HttpResponse(html)
#    #return HttpResponse('トップページです。')

def top(request):
    #html = loader.render_to_string('homepage/index.html')#トップページの読み込み
    #return HttpResponse(html)
    context = {
        'coordinator_list':Coordinator.objects.all(),
        'coordinator_list2':Coordinator2.objects.all(),
    }
    return render(request, 'homepage/index.html', context)

def coordinator(request):
    context = {
        'coordinator_list':Coordinator.objects.all(),
        'coordinator_list2':Coordinator2.objects.all(),
    }
    return render(request, 'homepage/coordinator.html', context)


def register(request):
    return render(request, 'homepage/register.html',)

def aboutus(request):
    return render(request, 'homepage/aboutus.html',)

def contact(request):
    return render(request, 'homepage/contact.html',)

def terms_of_service(request):
    return render(request, 'homepage/terms_of_service.html',)

def privacy_policy(request):
    return render(request, 'homepage/privacy_policy.html',)

    
#test
def myroom(request):
    context = {
        'myroom_list':Myroom.objects.get(pk=1),#一つ目のデータだけを渡す。
        'stock_list':Stock.objects.all(),
    }
    return render(request, 'homepage/myroom.html', context)

homepage/templates/homepage/aboutus.html
<!-- 共通テンプレートを継承 -->
{% extends 'homepage/base.html' %}

<!-- タブに表示される名前 -->
{% block title %}IDEAL ROOM{% endblock %}

{% load static %}<!-- Django用のスタティックフォルダアクセス用タグ読み込み -->
{% block content %}

    <!-- 本文のブロック -->
    <div class="contener"><!-- クラスを2つ指定 css用 -->            

        <!-- 事業内容のグループ -->
        <!-- ３つのサービス全体を囲むためのグループを作る -->
        <div class="container_service">

            <h1>会社紹介！</h1><!-- 見出し h1が無いので階層にするために上に作る（仮にロゴの下の文をh1とする） -->

        </div>
    </div>
        <!-- 本文 -->



{% endblock %} 

homepage/templates/homepage/base.html
<!-- 共通テンプレート -->

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><!-- 表示される幅についての規定 -->
    <title>{% block title %}{% endblock %}</title><!-- タブに表示される名前 テンプレートタグを使用 -->
    <meta name="description" content="IDEAL ROOM です。よろしくお願いします。"><!-- 検索した時に表示される表示内容 -->
    {% load static %}<!-- Django用のスタティックフォルダアクセス用タグ読み込み -->
    <link rel="stylesheet" href="{% static 'the-new-css-reset/css/reset.css' %}"><!-- reset.cssのディレクトリの相対パス -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"><!-- cssのディレクトリの相対パス -->
    
</head>


<body>

    <!-- まとめて扱うためにヘッダ部分をグルーピングする -->
    <header class="header"><!-- クラスを2つ指定 css用 -->

        <!-- まとめて扱うためにロゴ部分をグルーピングする -->
        <div class="logo">
            <!-- <img src="{% static 'img/logo.png' %}" alt="IDEAL ROOM"> -->
            <!-- altは表示されない時の代替 -->
            <h1>IDEAL ROOM</h1><!-- ロゴの下の文字 -->
        </div>
        
        <!-- メニュー リスト 順番を明示しない -->
        <nav>
        <ul>
            <!-- リスト リンクをつけたいのでaタグを入れておく -->
            <!-- リンクはURLのハードコーディングを避けるため、名前空間を作成 -->
            <li><a href="{% url 'homepage:top' %}">トップ</a></li>
            <li><a href="{% url 'homepage:coordinator' %}">コーディネーター</a></li>
            <li><a href="{% url 'homepage:register' %}">新規登録</a></li>
            <!-- <li><a href=""></a></li> -->
            <li><a href="{% url 'homepage:aboutus' %}">会社概要</a></li>
            <li><a href="{% url 'homepage:contact' %}">お問合せ</a></li>
        </ul>
        </nav>
    
    </header>


    <!-- 本文のブロック -->
    {% block content %}{% endblock %}
    


    <!-- フッターのグループ -->
    <footer class="footer">

        <div class="item-list">
            <div class="item">
                <a href="{% url 'homepage:terms_of_service' %}">利用規約</a>
            </div>
            <div class="item">
                <a href="{% url 'homepage:privacy_policy' %}">プライバシーポリシー</a>
            </div>
        </div>

        <div class="copy">
            &copy;2022 EVERY DAY
        </div>

    </footer>

</body>



</html>

homepage/templates/homepage/contact.html
<!-- 共通テンプレートを継承 -->
{% extends 'homepage/base.html' %}

<!-- タブに表示される名前 -->
{% block title %}IDEAL ROOM{% endblock %}

{% load static %}<!-- Django用のスタティックフォルダアクセス用タグ読み込み -->
{% block content %}

    <!-- 本文のブロック -->
    <div class="contener"><!-- クラスを2つ指定 css用 -->            

        <!-- 事業内容のグループ -->
        <!-- ３つのサービス全体を囲むためのグループを作る -->
        <div class="container_service">

            <h1>contact！</h1><!-- 見出し h1が無いので階層にするために上に作る（仮にロゴの下の文をh1とする） -->

        </div>
    </div>
        <!-- 本文 -->



{% endblock %} 

homepage/templates/homepage/coordinator.html
<!-- 共通テンプレートを継承 -->
{% extends 'homepage/base.html' %}

<!-- タブに表示される名前 -->
{% block title %}IDEAL ROOM{% endblock %}

{% load static %}<!-- Django用のスタティックフォルダアクセス用タグ読み込み -->
{% block content %}

    <!-- 本文のブロック -->
    <div class="contener"><!-- クラスを2つ指定 css用 -->            

        <!-- 事業内容のグループ -->
        <!-- ３つのサービス全体を囲むためのグループを作る -->
        <div class="container_service">

            <h1>あなたにぴったりのコーディネーターを探そう！</h1><!-- 見出し h1が無いので階層にするために上に作る（仮にロゴの下の文をh1とする） -->
            
            <!-- ３つのサービスを囲むためのグループを作る -->
            <div class="service_block">
                {% for coordinator in coordinator_list %}
                <div class="service">
                    <img src="{% static 'img/'|add:coordinator.picture %}" alt="サービス１"><!-- 画像 パスとquerySetを結合-->
                    <div class="ttl">{{ coordinator.name }}</div><!-- タイトル -->
                    <div class="frgn">{{ coordinator.furigana }}</div><!-- タイトル -->
                    <div class="explain">{{ coordinator.text }}</div><!-- 説明文 -->
                    <a href="">Profile</a><!-- リンク -->
                </div>
                {% endfor %}

            </div>
            <div class="service_block">
                {% for coordinator in coordinator_list2 %}
                <div class="service">
                    <img src="{% static 'img/'|add:coordinator.picture %}" alt="サービス１"><!-- 画像 -->
                    <div class="ttl">{{ coordinator.name }}</div><!-- タイトル -->
                    <div class="frgn">{{ coordinator.furigana }}</div><!-- タイトル -->
                    <div class="explain">{{ coordinator.text }}</div><!-- 説明文 -->
                    <a href="">Profile</a><!-- リンク -->
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
        <!-- 本文 -->



{% endblock %} 

homepage/templates/homepage/index.html
<!-- 共通テンプレートを継承 -->
{% extends 'homepage/base.html' %}

<!-- タブに表示される名前 -->
{% block title %}IDEAL ROOM{% endblock %}

{% load static %}<!-- Django用のスタティックフォルダアクセス用タグ読み込み -->
{% block content %}

    <!-- 本文のブロック -->
    <div class="contener"><!-- クラスを2つ指定 css用 -->            

        <!-- ヘッダー画像用のグループ -->
        <div class="header_img">
            <img src="{% static 'img/cat.jpg' %}" alt=""><!-- 説明がなければaltは必要ない -->
        </div>

        <p>その道のエキスパートと買う。<br>
            間違いないコーディネータ選択で、<br>
            お部屋での生活がもっと楽しくなる。</p>

        <div class="touroku_link">
            <span id="touroku">
                <a href="{% url 'homepage:register' %}">登録はこちらから</a><!-- リンク -->
            </span>
        </div>

        <!-- 事業内容のグループ -->
        <!-- ３つのサービス全体を囲むためのグループを作る -->
        <div class="container_service">

            <h1>あなたにぴったりのコーディネーターを探そう！</h1><!-- 見出し h1が無いので階層にするために上に作る（仮にロゴの下の文をh1とする） -->
            
            <!-- ３つのサービスを囲むためのグループを作る -->
            <div class="service_block">
                {% for coordinator in coordinator_list %}
                <div class="service">
                    <img src="{% static 'img/'|add:coordinator.picture %}" alt="サービス１"><!-- 画像 パスとquerySetを結合-->
                    <div class="ttl">{{ coordinator.name }}</div><!-- タイトル -->
                    <div class="frgn">{{ coordinator.furigana }}</div><!-- タイトル -->
                    <!-- <div class="explain">{{ coordinator.text }}</div><!-- 説明文 --> -->
                    <a href="">Profile</a><!-- リンク -->
                </div>
                {% endfor %}

            </div>
            <div class="service_block">
                {% for coordinator in coordinator_list2 %}
                <div class="service">
                    <img src="{% static 'img/'|add:coordinator.picture %}" alt="サービス１"><!-- 画像 -->
                    <div class="ttl">{{ coordinator.name }}</div><!-- タイトル -->
                    <!-- <div class="explain">{{ coordinator.text }}</div><!-- 説明文 --> -->
                    <a href="">Profile</a><!-- リンク -->
                </div>
                {% endfor %}

            </div>
        </div>

        <div class="coordinator_link">
            <span id="link">
                <a href="{% url 'homepage:coordinator' %}">Other Coordinator</a><!-- リンク -->
            </span>
        </div>

        <!-- 本文 -->


        <!-- ３つのサービス全体を囲むためのグループを作る -->
        <div class="service_group">

            <h2>How to Use</h2>

            <div class="service_block">
                <div class="service">
                    <a href="{% url 'homepage:register' %}"><img src="" alt="写真１"></a><!-- 画像 パスとquerySetを結合-->
                    <div class="ttl">どんな部屋が好みか<br>教えてください</div><!-- タイトル -->
                    <div class="explain">質問に答えて頂くことで、<br>あなたに最適な<br>コーディネーターを提案します。</div><!-- 説明文 -->
                    
                    
                </div>
                <div class="service">
                    <img src="" alt="写真２"><!-- 画像 パスとquerySetを結合-->
                    <div class="ttl">コーディネーターと<br>LINEで相談</div><!-- タイトル -->
                    <div class="explain">希望通りのデザインを<br>納得いくまで相談できます。</div><!-- 説明文 -->
                    
                    
                </div>
                <div class="service">
                    <img src="" alt="写真３"><!-- 画像 パスとquerySetを結合-->
                    <div class="ttl">継続的なサポート<br>　</div><!-- タイトル -->
                    <div class="explain">コーディネーターが見つかったら<br>継続的にサポートを依頼しよう。</div><!-- 説明文 -->
                    
                    
                </div>
            </div>



        
    </div>


{% endblock %} 

homepage/templates/homepage/privacy_policy.html
<!-- 共通テンプレートを継承 -->
{% extends 'homepage/base.html' %}

<!-- タブに表示される名前 -->
{% block title %}IDEAL ROOM{% endblock %}

{% load static %}<!-- Django用のスタティックフォルダアクセス用タグ読み込み -->
{% block content %}

    <!-- 本文のブロック -->
    <div class="contener"><!-- クラスを2つ指定 css用 -->            

        <!-- 事業内容のグループ -->
        <!-- ３つのサービス全体を囲むためのグループを作る -->
        <div class="container_service">

            <h1>プライバシーポリシー！</h1><!-- 見出し h1が無いので階層にするために上に作る（仮にロゴの下の文をh1とする） -->

        </div>
    </div>
        <!-- 本文 -->



{% endblock %} 

homepage/templates/homepage/register.html
<!-- 共通テンプレートを継承 -->
{% extends 'homepage/base.html' %}

<!-- タブに表示される名前 -->
{% block title %}IDEAL ROOM{% endblock %}

{% load static %}<!-- Django用のスタティックフォルダアクセス用タグ読み込み -->
{% block content %}

    <!-- 本文のブロック -->
    <div class="contener"><!-- クラスを2つ指定 css用 -->            

        <!-- 事業内容のグループ -->
        <!-- ３つのサービス全体を囲むためのグループを作る -->
        <div class="container_service">

            <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSd2p-ppnSjWBXRIDcMY3tsENj30qG824Fd86FghME25GHWNvg/viewform?embedded=true" width="1200" height="1200" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます…</iframe>

        </div>
    </div>
        <!-- 本文 -->



{% endblock %} 

homepage/templates/homepage/terms_of_service.html
<!-- 共通テンプレートを継承 -->
{% extends 'homepage/base.html' %}

<!-- タブに表示される名前 -->
{% block title %}IDEAL ROOM{% endblock %}

{% load static %}<!-- Django用のスタティックフォルダアクセス用タグ読み込み -->
{% block content %}

    <!-- 本文のブロック -->
    <div class="contener"><!-- クラスを2つ指定 css用 -->            

        <!-- 事業内容のグループ -->
        <!-- ３つのサービス全体を囲むためのグループを作る -->
        <div class="container_service">

            <h1>利用規約！</h1><!-- 見出し h1が無いので階層にするために上に作る（仮にロゴの下の文をh1とする） -->

        </div>
    </div>
        <!-- 本文 -->



{% endblock %} 